[package]
name = "enemy"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.15.1"
models = { path = "../models" }
castle = { path = "../castle" }
bevy_rapier2d  = { version = "0.28.0",  features = ["wasm-bindgen"] }
